### PR TITLE
add alternate asynchronous db ops

### PR DESCRIPTION
**Pull request by r2evans**
alternate method for future'd database operations

### CODE REVIEW

**Comment by blairj09** [comment]
@r2evans unfortunately, this approach has no benefit. Every future runs in a separate process so the connection is never persisted and is still created with every query.

I updated the shinyloadtest report to include an identical loadtest run against your solution, and the results are nearly identical to the existing async solution (in fact, async2 is slightly slower). 

image


image

I also added logging to the `conn` function which shows that every call to `conn` creates a new connection - an existing connection is never available.

```
2020/06/30 23:15:20.775889764 .con does not exist. Creating .con
2020/06/30 23:15:25.339898440 .con does not exist. Creating .con
2020/06/30 23:15:32.458794297 .con does not exist. Creating .con
...
2020/06/30 23:38:34.096774054 .con does not exist. Creating .con
2020/06/30 23:38:37.146957256 .con does not exist. Creating .con
2020/06/30 23:38:40.280363189 .con does not exist. Creating .con
```

Details about the dangers of reusing DB connections within future operations are detailed in part [here](https://rstudio.github.io/promises/articles/futures.html#native-resources).

**Comment by r2evans** [comment]
I understand, but ... there is something wrong with the premise or the mechanics of that load test.

1. I see reused connections all the time, so the fact that you're seeing newly-created connections each time is interesting (and atypical).
2. While the plots suggest that times don't change, I *promise* (and `promise` :-) you that without async database queries, all of the users have a very different experience. The moment any user has to wait 15-20 seconds while the R side of things is unresponsive, they complain loudly (as they should). (Things like `plotly` might still work, as long as there are no callbacks.)

Perhaps I'm misunderstanding `future` here: is it just making a call and then exiting? That is the only thing that I see that might explain why a previous connection is not available.

(I don't understand why you linked to "native resources": I never attempt to transfer a connection object to the child processes, just the connection arguments.)

**Comment by hadley** [comment]
This code might work for you, but I have a very hard to time understanding _how_ it works — I think that's dangerous because there's some chance that it works by coincidence rather than working on purpose. In particular, I have very hard time understanding the essence of the approach:

```R
conn <- function(args) {
  if (!exists(".con")) .con <<- do.call(DBI::dbConnect, eval(dbargs))
  return(.con)
}
dbargs <- substitute(list(drv = RSQLite::SQLite(), "tmp.sqlite"))

future(conn(dbargs))
```

Firstly, I'm confused by `conn()` taking `args` but not actually using them; but I think that's just a typo, and you meant:

```R
conn <- function(args) {
  if (!exists(".con")) .con <<- do.call(DBI::dbConnect, eval(args))
  return(.con)
}
dbargs <- substitute(list(drv = RSQLite::SQLite(), "tmp.sqlite"))
```

So what exactly happens when `conn(dbargs)` is called? I understand what happens if you call it in the current process: the first time it is called it will create an object called `.con` in the global environment, and the second and subsequent calls it will return the object. Even in a single process I think this is a bit dangerous because if you use this technique elsewhere, you have to remember to use a name other name `.con`.  And if this is a long running process (which is presumably the point), then `.con` is likely to timeout at some point, so you really should be using pool or similar here.

What happens when it's called by `future()`? I think this depends critically on how future works — does it start a process, leave it running and reuse it, or are the processes long-running? If so, how many processes are in the pool? How does it manage objects that you create in the global environment? You also never close those database connections, which is unlikely to make your DBA happy.

I suspect you'd get most of the benefit with a much much simpler execution model like this:

```R
db_connect <- function(...) {
  DBI::dbConnect(RSQLite::SQLite(), "tmp.sqlite")
}

future({
  con <- db_connect()
  on.exit(DBI::dbDisconnect(con))
  
  DBI::dbGetQuery(con, "
    WITH RECURSIVE r(i) AS (
       VALUES(0)
       UNION ALL
       SELECT i FROM r
       LIMIT 10000000
     )
     SELECT i FROM r WHERE i = 1;
  ")
})
```

(Also note that I extract the database connection code into a function — I think that's a safer/simpler approach than messing with `substitute()` + `eval()`).

**Comment by r2evans** [comment]
This repo/PR is missing some points that are contained in an email conversation with Tonya Filz and Katie Masiello. For that conversation, I was leaning towards code-golf and simplicity, excluding unnecessary components. My apologies for omitting some salient points.

# Background

For context, the conversation started with a pain point with some of our apps: long queries (10-30sec) in the foreground freeze shiny for all connected users. (This is not a surprise, I'm familiar with discussions about threading/multi-processes. See *"Pain Point"* below for a little more context.)

With "normal" operations, this is a clear call for `future`/`promise`. Here, though, we need to contend with the fact that connection objects cannot be transferred to child processes, so we devised a method wherein there is always a connection in the current process.

While not formally categorized, we have some queries that are ultra-quick, some that are rather long, and then the rest. Ultimately there are a dozen or so queries in each app. The ultra-quick queries tend to always run in the parent process. For the rest, even not-long queries can be subject to a perfect storm of concurrent users to produce noticeable UX lag. In order to simplify connection management, we chose to *not* assume that the query is in the parent process; with this, a query can easily be done in the parent or the child without changing the connection method.

(For a little context, a significant portion of our apps' use is "surge", where multiple users connect simultaneously immediately after a race finishes.)

I do not want to add "connect" time (often 1-2 seconds, uncertain why it so much) to query times (though this might be a wash with the long queries). If starting a connection was nearly-instantaneous or added nothing to the query time, then I would simply sandwich every DB operation with `dbConnect`/`dbDisconnect` and avoid connection management altogether.

Ergo the hack for always having a persistent connection in each process.

# This PR

- Big oops, yes, use of `args`/`dbargs` is a typo. No real surprise it works, but it's a mistake.

- Since `dbargs` is transferred to all child processes, every time `conn(dbargs)` is called in any process (original or child), it uses an existing connection if found in the *current* global env; if not found, it creates it and stores it for the next time. It behaves the same whether in the parent process or a child process. In my use, it does not create a connection each time, not sure why the load test demonstrates otherwise.

- I'm already using `pool`. This repo/app (without `pool`) was meant to be a tiny demonstration on the effect long query times are having on multiple users.

- The future pool is generally 3+ or so. For the most part, the futures are used for longer calculations, not just database queries. Other than startup (where some global objects are automatically transferred), we honor [promises/shiny](https://rstudio.github.io/promises/articles/shiny.html) for safe-guarding objects intended for the promise, and/or we explicitly start `future` ops with explicit data.

# Connection management

[`async/app.R`](https://github.com/blairj09/shiny-query-async/blob/master/R/async/app.R#L27) suggested connecting, querying, and disconnecting with each query. This is not the first time I've seen preference for creating a new connection with every query, though I've not seen that recommendation for "production". I believe this is *not* the general recommendation for single-process workflows, why should that be fundamentally different in parallel? The fact that we need to manage the connections a little more carefully is not a surprise to me.

If it matters, in our shiny apps, the `conn()` function is actually storing the connection in its own surrounding environment, not in the global, ala

```r
conn <- local({
  .con <- NULL
  function(args) {
    if (is.null(".con")) .con <<- do.call(DBI::dbConnect, eval(args))
    return(.con)
  }
})
```

I don't think that this scope difference would change the load test results. Am I missing something? I believe this approach to be relatively safe, though I don't often see it in the wild.

# Pain Point

The original "pain point" I mentioned has to do with failures in backgrounded code. I am familiar with how RSC (RStudio Connect) logs (`./jobs/**/job.*`), but occasionally there is a failure that is "clearly" in a parallel promise but the error itself does not appear in any logs (perhaps it fails too quickly, I don't know why, but it clearly failed). I have been trying to narrow down the source of the bug (e.g., logging, `tryCatch`), and they suggest connectivity problems (whether a bug in `DBI`, `odbc`, `pool`, the DBMS, or something else ... broad scope). It does not fail in local single-process (`plan(sequential)`) testing, but while not perfectly reproducible it does recur.

I'm not asking your help to troubleshoot *that* problem, I have no idea where you could begin. 

When it suggested connectivity problems, I sought to validate our method for `future`ing SQL connections/queries. I don't immediately see a hole in the logic of the above `conn(dbargs)` (other than my typo and what your load test demonstrates), but since I have not found "best practices" for connection management using `future` and `pool`, Katie's outreach sparked the conversation.

**Comment by jcheng5** [comment]
`dbConnect` taking 1-2 seconds is surprising to me, and it makes more sense to me now why you're working so hard to reuse connections.

`plan(multiprocess)` works differently on Mac/Linux vs. Windows, on Mac/Linux I think attempting to reuse connections makes no sense but on Windows it does because the same worker processes are reused.

On Windows:

```
> plan(multiprocess)
> value(future(Sys.getpid()))
[1] 3316
> value(future(Sys.getpid()))
[1] 3316
> value(future(Sys.getpid()))
[1] 3316
```

On Mac:

```
> plan(multiprocess)
> value(future(Sys.getpid()))
[1] 78746
> value(future(Sys.getpid()))
[1] 78748
> value(future(Sys.getpid()))
[1] 78749
```

So that totally makes sense to me. I'd change `plan(multiprocess)` to `plan(multisession)`, which will then ensure that you get the same behavior you see on Windows when this is deployed to the server.

One change you might consider is to take extra care to ensure the saved connection is *never* reused across boundaries by saving the pid with it (warning, not tested):

```r
conn <- local({
  .con <- NULL
  .pid <- NULL
  function(args) {
    if (is.null(".con") || !identical(.pid, Sys.getpid())) {
      .con <<- do.call(DBI::dbConnect, eval(args))
      .pid <<- Sys.getpid()
    }
    return(.con)
  }
})
```

I only say this because I couldn't tell you for sure whether I'd expect that closure's environment to be copied into the worker process, and I worry that it only is or isn't due to race conditions about whether or not `conn()` is called in the parent process before the workers are spawned.

**Comment by r2evans** [comment]
Great points.

- The 1-2 second connection time is both perplexing and (I think) out of my hands: I suspect (for lack of any other evidence) that the culprit there is related to the DBMS itself and nothing inherent to R. (I've had over 4 second pauses when connecting, though that's really rare.)

- I like your summary of `multiprocess` versus `multisession`, thank you. I think I had taken some of Henrik's comments to mean the same thing, and leaned towards using `plan(multisession)` in production. Only now do I recognize that I had kept `plan(multiprocess)` in my PR for `async2`, I think that explains some of the different behavior.

- I like your suggestion for `.pid`, thank you!

**Comment by hadley** [comment]
Alternatively, you could make the caching environment much more explicit, so it's clear how it's being reused across future workers:

```R
cache %<-% new.env(parent = emptyenv())
conn %<-% function(args) {
    if (is.null(cache$con)) {
      cache$con <- db_connect()
    }
    cache$con
  }
})
```

(I'm mostly guessing at the future syntax here; I didn't run this code)

You're still at the mercy of understanding the precise process model of future, but it's a lot more explicit.

**Comment by r2evans** [comment]
I haven't played sufficiently with `%<-%` to be proficient with it yet, I'll look into that. Thank you @hadley.

**Pull request merged**
